[project]
name = "BCAM_intern_project"
version = "0.1.0"
description = "Código para el proyecto realizado durante las prácticas de BCAM"
# ¡OJO! Aquí NO va la lista de packages.
# Puedes añadir dependencias si quieres:
dependencies = [
    "numpy",
    "qiskit_aer",
    "qiskit",
    "matplotlib",
    "plotly"
]

[tool.setuptools]
# AQUÍ es donde defines qué carpetas son código.
# He visto que añadiste "LightFrontQCD", ¡perfecto!
packages = ["Dynamics", "Topology"]

